---
name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run go test
        run: go test -v -race ./...

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.1
          args: --enable=gofumpt,goimports,whitespace,gocritic,exportloopref,unconvert,ifshort,prealloc
