---
name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Run go test
        run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 1.46
          args: --enable=goimports,gofumpt,whitespace,exportloopref
